spring:
  datasource:
    url: jdbc:mysql://localhost:3306/udemy_blog_application
    username: root
    password: root
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: update
    show-sql: true
#  security:
#    user:
#      name: user
#      password: password
#      roles: ADMIN
logging:
  level:
    org:
      springframework:
        security: DEBUG
#JWT
app:
  jwt-secret: JWTSecretKey
  jwt-expiration-milliseconds: 604800000